--- 
abstract: ~
author: Kang-min Liu  C<< <gugod@gugod.org> >>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-CSSQuery
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBD::SQLite: 0
  DBI: 0
  Sub::Exporter: 0
  perl: 5.8.0
  self: 0.15
version: 0.01
